### ISSUE TITLE
test - o2arcex.py, o2arc_check.py 실행 오류

### ISSUE THREAD

**Issue by Seondong** [ConfeitoHS/arcle#4]
[o2arc_check.py](https://github.com/ConfeitoHS/arcle/blob/main/tests/o2arc_check.py)와 [o2arcex.py](https://github.com/ConfeitoHS/arcle/blob/main/tests/o2arcex.py)을 실행하면 다음과 같은 에러가 뜹니다.

```
(base) sundong@172 arcle % python tests/o2arc_check.py  
Traceback (most recent call last):
  File "/Users/sundong/Documents/mldl-code/arcle-agent/arcle/tests/o2arc_check.py", line 147, in <module>
    obs, info = env.reset(options= {'adaptation':False, 'prob_index':findbyname(traces_info[idx][0]), 'subprob_index': traces_info[idx][1]})
  File "/Users/sundong/anaconda3/lib/python3.10/site-packages/gymnasium/wrappers/order_enforcing.py", line 61, in reset
    return self.env.reset(**kwargs)
  File "/Users/sundong/anaconda3/lib/python3.10/site-packages/gymnasium/wrappers/env_checker.py", line 57, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/Users/sundong/anaconda3/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py", line 186, in env_reset_passive_checker
    result = env.reset(**kwargs)
  File "/Users/sundong/Documents/mldl-code/arcle-agent/arcle/arcle/envs/base.py", line 95, in reset
    ex_in, ex_out, tt_in, tt_out, desc = self.loader.pick(data_index=self.prob_index)
  File "/Users/sundong/Documents/mldl-code/arcle-agent/arcle/arcle/loaders/loader.py", line 45, in pick
    assert self.data is not None and len(self.data)>0, "Dataset wasn't loaded properly"
AssertionError: Dataset wasn't loaded properly
```

**Comment by ConfeitoHS** [comment]
Hello, It seems that there is a problem related to absolute path. Would you unzip and install this `.whl` package manually and test again?

It can be installed by `pip install arcle-0.2.5.post4-py3-none-any.whl` .
[arcle-0.2.5.post4-py3-none-any.zip](https://github.com/ConfeitoHS/arcle/files/13765853/arcle-0.2.5.post4-py3-none-any.zip)

**Comment by bhumikach8989** [comment]
Hello Sir,
I am an M.Tech student currently using the ARCLE environment for my project.

When I try to run the examples bbox.py and bboxmini.py provided in the ARCLE repository, I encounter the following error:
**AttributeError: 'BBoxWrapper' object has no attribute 'H'**

This error occurs immediately when calling env = BBoxWrapper(env).

I have verified that the environment is correctly installed. It seems like the wrapper is trying to access an attribute H that is either missing or not properly initialized.

Could you please help resolve this issue?

Environment Details:

ARCLE version: [e.g. 0.2.6]

Python version: [e.g., 3.11]

Gymnasium version: [e.g., 1.2.0]

Thank you in advance for your support.

<img width="977" height="302" alt="Image" src="https://github.com/user-attachments/assets/a69228d0-2ed6-4028-9096-397b4cfaca5f" />

<img width="798" height="329" alt="Image" src="https://github.com/user-attachments/assets/4dd3c20a-302b-4da5-ae63-d50efbe8bdd3" />
